### ISSUE TITLE
[1.18.2] Mod incompatibility

### ISSUE THREAD

**Issue by dr3ams** [JDKDigital/golemsarefriends#1]
Added it to a modpack: [Life in the village 3](https://www.curseforge.com/minecraft/modpacks/life-in-the-village-3)
and it started to crash on startup.

Crash report: https://gist.github.com/dr3ams/5919678488e5f570136cd73c0260e99b
Latest.log: https://gist.github.com/dr3ams/a4df598369ba6620b964cab7b7b28612

**Comment by JaisDK** [comment]
It looks to be an incompatibility with something in Alex's Mobs, I'll investigate more later.

[10:11:12] [Render thread/ERROR]: Exception caught during firing event: Could not initialize class net.minecraft.world.entity.npc.Villager
	Index: 1
	Listeners:
		0: NORMAL
		1: ASM: class com.github.alexthe666.alexsmobs.entity.AMEntityRegistry initializeAttributes(Lnet/minecraftforge/event/entity/EntityAttributeCreationEvent;)V
java.lang.NoClassDefFoundError: Could not initialize class net.minecraft.world.entity.npc.Villager

**Comment by JaisDK** [comment]
The incompatibility is with productive villagers. Unfortunately they have hidden sources, so I can't see what they are doing.

**Comment by JaisDK** [comment]
I'm uploading a new version with less mixin, it loads fine in LITV3 for me.

**Comment by JaisDK** [comment]
https://www.curseforge.com/minecraft/mc-mods/golemsarefriends/files/4088012
